name: 'Release'
run-name: 'Create SDL release artifacts for ${{ inputs.commit }}'

on: [push, pull_request]
# on:
#   workflow_dispatch:
#     inputs:
#       commit:
#         description: 'Release'
#         required: true

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Build'
        id: releaser
        shell: bash
        run: |
          cmake -S . -B build -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_BUILD_TYPE=Release
          cd build
          make
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "windows.tar.gz,build/libSDL3.a"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}

  windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Build'
        run: |
          cmake -S . -B build -DSDL_SHARED=OFF -DSDL_STATIC=ON -DCMAKE_BUILD_TYPE=Release
          cmake --build build
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "windows.tar.gz,build/Debug/SDL3-static.lib"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}